<?php

return [

    'opescare' => [
        'slug' => 'opescare',
        'name' => 'OPESCare',
        'subtitle' => 'Health ID · Interoperability Layer',
        'category' => 'Core Platform',
        'icon' => 'fingerprint',
        'color' => '#00C896',
        'tagline' => 'One universal Health ID for every patient — connecting all 22 OPES systems and every facility they visit.',
        'description' => 'OPESCare is the backbone of the OPES ecosystem. It assigns every patient a permanent, unique Health ID at their very first contact with any OPES-connected facility, then follows them for life — through every clinic visit, hospital admission, lab test, prescription, and specialist referral, across any participating facility in Cameroon and the CEMAC region.',
        'description2' => 'Built on HL7 FHIR R4 standards, OPESCare acts as the interoperability hub that connects all 22 OPES software systems. When a patient registered at a clinic in Douala visits a hospital in Yaoundé, their complete history is immediately available — no re-registration, no duplicate tests, no lost records.',
        'target_users' => [
            'Hospital networks operating across multiple sites',
            'National and regional health authorities managing population data',
            'Any facility deploying two or more OPES software systems',
            'NGOs and government programmes requiring patient tracking',
            'Insurance and CNPS partners needing verified patient identity',
        ],
        'problems_solved' => [
            ['title' => 'Duplicate patient records across facilities', 'desc' => 'One Health ID eliminates re-registration and duplicate data entry at every new facility.'],
            ['title' => 'Fragmented medical histories', 'desc' => 'Lab results, prescriptions, and diagnoses from any connected facility appear in one unified record.'],
            ['title' => 'Inability to track patients across the care continuum', 'desc' => 'Follow a patient from primary clinic through specialist referral, hospitalisation, and discharge in one system.'],
            ['title' => 'No population health data for Ministry reporting', 'desc' => 'Aggregated, de-identified data feeds directly into HMIS and public health dashboards.'],
        ],
        'stats' => [
            ['value' => '22', 'label' => 'connected OPES systems'],
            ['value' => 'HL7 FHIR', 'label' => 'interoperability standard'],
            ['value' => 'EN/FR', 'label' => 'fully bilingual'],
            ['value' => 'CEMAC', 'label' => 'regional coverage'],
        ],
        'modules' => [
            ['icon' => 'fingerprint', 'name' => 'Health ID Issuance', 'desc' => 'Assign a unique, permanent Health ID at first contact via biometric, photo, or demographic matching.', 'features' => ['Biometric deduplication', 'Photo capture & verification', 'QR code & printed card', 'Instant cross-facility lookup']],
            ['icon' => 'network', 'name' => 'Interoperability Hub', 'desc' => 'FHIR R4 API layer connecting all OPES systems and enabling data exchange with external platforms.', 'features' => ['HL7 FHIR R4 endpoints', 'Real-time event notifications', 'Batch data import/export', 'External system connectors']],
            ['icon' => 'shield', 'name' => 'Consent & Privacy', 'desc' => 'Patient-controlled data sharing permissions with full audit trail on every access.', 'features' => ['Granular sharing consent', 'Access revocation', 'Full audit log', 'GDPR / local regulation ready']],
            ['icon' => 'bar-chart-2', 'name' => 'Population Health Analytics', 'desc' => 'Anonymised aggregate dashboards for disease surveillance, MoH HMIS reporting, and public health planning.', 'features' => ['Disease burden mapping', 'MoH HMIS export', 'Epidemiology alerts', 'Facility performance comparison']],
        ],
        'workflow' => [
            ['step' => 'First Contact', 'desc' => 'Patient registers at any OPES facility'],
            ['step' => 'ID Issued', 'desc' => 'Unique Health ID created instantly'],
            ['step' => 'Record Grows', 'desc' => 'Every visit, test & prescription appended'],
            ['step' => 'Any Facility', 'desc' => 'Instant lookup at any connected site'],
            ['step' => 'Lifetime Record', 'desc' => 'Complete history always available'],
        ],
        'benefits' => [
            ['icon' => 'link', 'color' => '#00C896', 'title' => 'One record, every facility', 'desc' => 'No re-registration. No lost history. The patient\'s full record is available the moment they arrive anywhere in the network.'],
            ['icon' => 'shield-check', 'color' => '#1A6FE8', 'title' => 'Built-in interoperability', 'desc' => 'HL7 FHIR R4 ensures OPESCare communicates not just with OPES systems but with any standards-compliant external platform.'],
            ['icon' => 'landmark', 'color' => '#00C896', 'title' => 'Ministry-ready reporting', 'desc' => 'Population health data feeds directly into Cameroon MoH HMIS formats — compliance built in from day one.'],
            ['icon' => 'globe-2', 'color' => '#1A6FE8', 'title' => 'CEMAC-scale design', 'desc' => 'Designed to operate across national borders within the CEMAC region, supporting cross-border patient mobility.'],
        ],
        'integrations' => ['opes-emr', 'opes-hospital-his', 'opes-lab', 'pharmis', 'radis', 'opes-triage', 'uhc-is'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud · Hybrid'], ['key' => 'Minimum server', 'val' => '4 vCPU, 8 GB RAM'], ['key' => 'Database', 'val' => 'MySQL 8 / PostgreSQL 15'], ['key' => 'Offline mode', 'val' => 'Supported (queue sync)']]],
            ['group' => 'Interoperability', 'rows' => [['key' => 'Standard', 'val' => 'HL7 FHIR R4'], ['key' => 'Terminology', 'val' => 'ICD-10 · ICD-11 · SNOMED CT'], ['key' => 'API', 'val' => 'RESTful JSON + FHIR'], ['key' => 'Import formats', 'val' => 'CSV · HL7 v2 · FHIR Bundles']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'MFA · SSO (SAML 2.0)'], ['key' => 'Audit logging', 'val' => 'Every access logged'], ['key' => 'Data residency', 'val' => 'In-country (Cameroon) option']]],
        ],
        'related' => ['opes-emr', 'opes-hospital-his', 'opes-triage'],
    ],

    'opes-emr' => [
        'slug' => 'opes-emr',
        'name' => 'OPES EMR',
        'subtitle' => 'Electronic Medical Records · Clinics & Hospitals',
        'category' => 'Core Platform',
        'icon' => 'stethoscope',
        'color' => '#00C896',
        'tagline' => 'Africa\'s most comprehensive bilingual EMR — built for the way clinicians in Cameroon actually work.',
        'description' => 'OPES EMR is a fully bilingual (English/French) electronic medical records system designed specifically for hospitals, clinics, and health centres in Cameroon, the CEMAC region, and across Africa. Unlike imported systems retrofitted for local use, OPES EMR was designed from the ground up around how African healthcare facilities actually operate.',
        'description2' => 'It captures the complete patient journey — from first contact through diagnosis, treatment, prescriptions, laboratory and radiology orders, billing, and long-term follow-up — in one connected record. Integrated natively with OPESCare Health ID, every clinician can access a patient\'s full history across every OPES-connected facility.',
        'target_users' => [
            'District hospitals and general clinics (10–500 beds)',
            'Private polyclinics and specialist centres',
            'Community health centres running government UHC programmes',
            'NGO-operated facilities seeking interoperable reporting',
            'Hospital networks wanting one unified patient record across branches',
        ],
        'problems_solved' => [
            ['title' => 'Paper records lost or inaccessible', 'desc' => 'OPES EMR creates a permanent, searchable digital record from day one.'],
            ['title' => 'Duplicate tests across facilities', 'desc' => 'OPESCare Health ID links every result and prescription across every connected facility.'],
            ['title' => 'Language barriers in bilingual regions', 'desc' => 'Every screen, form, and report is available in English and French simultaneously.'],
            ['title' => 'Disconnected departments', 'desc' => 'Lab, pharmacy, radiology, and billing all read from and write to the same patient record in real time.'],
            ['title' => 'No Ministry reporting', 'desc' => 'OPES EMR generates HMIS reports in the formats required by the Cameroon Ministry of Health.'],
        ],
        'stats' => [
            ['value' => '12', 'label' => 'core modules'],
            ['value' => 'EN/FR', 'label' => 'fully bilingual interface'],
            ['value' => 'HL7 FHIR', 'label' => 'interoperability standard'],
            ['value' => '22', 'label' => 'OPES systems connected'],
        ],
        'modules' => [
            ['icon' => 'user-plus', 'name' => 'Patient Registration', 'desc' => 'Capture complete demographics and issue a unique patient ID linked to OPESCare Health ID.', 'features' => ['Photo & biometric capture', 'Insurance & CNPS enrolment', 'Walk-in & pre-booked registration', 'Auto-link to OPESCare Health ID']],
            ['icon' => 'calendar', 'name' => 'Appointment & Scheduling', 'desc' => 'Manage outpatient appointments, specialist referrals, and follow-up scheduling.', 'features' => ['Multi-provider calendar views', 'SMS & WhatsApp reminders', 'Waiting room queue display', 'Inter-department referral tracking']],
            ['icon' => 'file-pen-line', 'name' => 'Clinical Consultation (SOAP)', 'desc' => 'Structured SOAP notes with clinical decision support and ICD-10/11 coded diagnoses.', 'features' => ['Subjective, Objective, Assessment, Plan', 'ICD-10 / ICD-11 diagnosis coding', 'Specialty-specific template library', 'Voice-to-text note entry']],
            ['icon' => 'pill', 'name' => 'Prescription Management', 'desc' => 'Issue digital prescriptions with drug-interaction checking, routed directly to PHARMIS.', 'features' => ['Drug interaction & allergy alerts', 'Generic / brand substitution prompts', 'Direct push to PHARMIS pharmacy', 'Printable & electronic Rx']],
            ['icon' => 'activity', 'name' => 'Vital Signs & Monitoring', 'desc' => 'Record and track vital signs over time with visual trend graphs and automatic alerts.', 'features' => ['BP, pulse, temp, SpO2, weight, BMI', 'Trend graphs per visit and over time', 'Nurse triage integration', 'Wearable device import support']],
            ['icon' => 'bar-chart-2', 'name' => 'Reports & Analytics', 'desc' => 'Built-in dashboards for clinical indicators and Ministry of Health HMIS data submissions.', 'features' => ['Morbidity & mortality reports', 'MoH HMIS data export formats', 'Provider productivity dashboards', 'Custom date-range filtering']],
        ],
        'workflow' => [
            ['step' => 'Arrival', 'desc' => 'Registered or found by Health ID'],
            ['step' => 'Triage', 'desc' => 'Nurse records vitals & assigns priority'],
            ['step' => 'Consultation', 'desc' => 'Doctor writes SOAP note & diagnoses'],
            ['step' => 'Orders', 'desc' => 'Lab, imaging & prescriptions placed'],
            ['step' => 'Results', 'desc' => 'Lab & imaging return to record'],
            ['step' => 'Billing', 'desc' => 'Invoice auto-built from all acts'],
            ['step' => 'Discharge', 'desc' => 'Summary issued, follow-up scheduled'],
        ],
        'benefits' => [
            ['icon' => 'zap', 'color' => '#00C896', 'title' => 'Faster care delivery', 'desc' => 'Structured templates and real-time results cut consultation admin by up to 60%.'],
            ['icon' => 'link', 'color' => '#1A6FE8', 'title' => 'Truly connected records', 'desc' => 'Lab, pharmacy, radiology, and billing see the same data simultaneously.'],
            ['icon' => 'shield-check', 'color' => '#00C896', 'title' => 'Compliance built in', 'desc' => 'MoH HMIS reporting, ICD-10/11 coding, and HL7 FHIR — not bolted on after the fact.'],
            ['icon' => 'languages', 'color' => '#1A6FE8', 'title' => 'Bilingual by design', 'desc' => 'Every screen, form, and report available in English and French — switch mid-session.'],
        ],
        'integrations' => ['opescare', 'opes-lab', 'pharmis', 'radis', 'opes-triage', 'rcmis'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud · Hybrid'], ['key' => 'Minimum server', 'val' => '4 vCPU, 8 GB RAM'], ['key' => 'Database', 'val' => 'MySQL 8 / PostgreSQL 15'], ['key' => 'Offline mode', 'val' => 'Supported (queue sync)']]],
            ['group' => 'Interoperability', 'rows' => [['key' => 'Standard', 'val' => 'HL7 FHIR R4'], ['key' => 'Imaging', 'val' => 'DICOM 3.0'], ['key' => 'Terminology', 'val' => 'ICD-10 · ICD-11 · LOINC'], ['key' => 'API', 'val' => 'RESTful JSON + FHIR']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'MFA · SSO (SAML 2.0)'], ['key' => 'Audit logging', 'val' => 'Every record access logged'], ['key' => 'MoH compliance', 'val' => 'Cameroon HMIS aligned']]],
        ],
        'related' => ['opescare', 'opes-triage', 'opes-hospital-his'],
    ],

    'opes-hospital-his' => [
        'slug' => 'opes-hospital-his',
        'name' => 'OPES Hospital HIS',
        'subtitle' => 'Full Hospital Information System',
        'category' => 'Core Platform',
        'icon' => 'hospital',
        'color' => '#00C896',
        'tagline' => 'Complete hospital management from admissions to discharge — inpatient, theatre, wards, nursing, and billing in one system.',
        'description' => 'OPES Hospital HIS is a full hospital information system designed for large facilities — referral hospitals, regional hospitals, and multi-department private hospitals. It goes beyond the EMR to manage the entire inpatient journey: bed management, ward rounds, theatre scheduling, nursing care plans, pharmacy dispensing, and discharge summaries.',
        'description2' => 'Built on the same OPESCare interoperability layer, it connects seamlessly with OPES EMR for outpatient records, OPES Lab, PHARMIS, RADIS, and RCMIS — giving hospital administrators, clinicians, and finance teams a single unified view of every patient at every point in their journey.',
        'target_users' => [
            'Regional and referral hospitals (100+ beds)',
            'Multi-department private hospitals',
            'Military and parastatal hospital facilities',
            'Teaching hospitals requiring trainee tracking',
            'Hospital groups with multiple campuses',
        ],
        'problems_solved' => [
            ['title' => 'No visibility over bed occupancy in real time', 'desc' => 'Live bed management board shows every ward, bed status, and patient in one screen.'],
            ['title' => 'Theatre scheduling conflicts and delays', 'desc' => 'Integrated theatre management with surgeon, anaesthetist, and equipment scheduling.'],
            ['title' => 'Nursing care not documented or audited', 'desc' => 'Structured nursing care plans, medication administration records, and shift handover notes.'],
            ['title' => 'Discharge summaries take days to produce', 'desc' => 'Auto-generated discharge summary from the full inpatient record — ready at the bedside.'],
        ],
        'stats' => [
            ['value' => '100+', 'label' => 'bed capacity supported'],
            ['value' => 'Real-time', 'label' => 'ward & bed visibility'],
            ['value' => 'Theatre', 'label' => 'scheduling module'],
            ['value' => '22', 'label' => 'OPES systems connected'],
        ],
        'modules' => [
            ['icon' => 'bed', 'name' => 'Bed & Ward Management', 'desc' => 'Real-time bed board across all wards with admission, transfer, and discharge workflows.', 'features' => ['Live bed occupancy board', 'Ward-to-ward transfers', 'Isolation & specialty bed flags', 'Census & occupancy reports']],
            ['icon' => 'scissors', 'name' => 'Theatre Management', 'desc' => 'Full surgical scheduling with surgeon, anaesthetist, instrument, and recovery room management.', 'features' => ['Elective & emergency theatre lists', 'Pre-op checklist & consent', 'Anaesthesia records', 'Recovery room handover']],
            ['icon' => 'clipboard-list', 'name' => 'Nursing Care Plans', 'desc' => 'Structured nursing documentation including care plans, medication administration, and shift notes.', 'features' => ['NCP templates by speciality', 'Medication administration record (MAR)', 'Shift handover notes', 'Pain & wound assessment charts']],
            ['icon' => 'file-text', 'name' => 'Discharge Management', 'desc' => 'Auto-generated discharge summaries from the complete inpatient record, including referral letters.', 'features' => ['Auto-populated discharge summary', 'Medication reconciliation', 'Follow-up scheduling', 'Printed & electronic handover letter']],
        ],
        'workflow' => [
            ['step' => 'Admission', 'desc' => 'Patient admitted from OPD or emergency'],
            ['step' => 'Bed Assigned', 'desc' => 'Ward & bed allocated on live board'],
            ['step' => 'Ward Round', 'desc' => 'Doctor records daily notes & orders'],
            ['step' => 'Theatre (if needed)', 'desc' => 'Surgical scheduling & intra-op records'],
            ['step' => 'Nursing Care', 'desc' => 'MAR, care plans, shift notes'],
            ['step' => 'Discharge', 'desc' => 'Summary generated, bed freed'],
        ],
        'benefits' => [
            ['icon' => 'layout-grid', 'color' => '#00C896', 'title' => 'Full facility visibility', 'desc' => 'Every bed, ward, theatre, and patient — visible in real time from a single dashboard.'],
            ['icon' => 'clipboard-check', 'color' => '#1A6FE8', 'title' => 'Structured nursing care', 'desc' => 'Nursing documentation is built into the workflow — not an afterthought or a separate system.'],
            ['icon' => 'zap', 'color' => '#00C896', 'title' => 'Faster discharge', 'desc' => 'Auto-generated discharge summaries reduce the time from decision-to-discharge to minutes.'],
            ['icon' => 'link', 'color' => '#1A6FE8', 'title' => 'Seamless EMR integration', 'desc' => 'Inpatient records link directly to the outpatient EMR — one complete patient story.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-lab', 'pharmis', 'radis', 'rcmis'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud · Hybrid'], ['key' => 'Minimum server', 'val' => '8 vCPU, 16 GB RAM'], ['key' => 'Concurrent users', 'val' => 'Up to 500 per instance'], ['key' => 'Offline mode', 'val' => 'Partial (critical modules)']]],
            ['group' => 'Interoperability', 'rows' => [['key' => 'Standard', 'val' => 'HL7 FHIR R4'], ['key' => 'Imaging', 'val' => 'DICOM 3.0'], ['key' => 'Theatre', 'val' => 'HL7 v2 scheduling'], ['key' => 'API', 'val' => 'RESTful JSON + FHIR']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'MFA · SSO (SAML 2.0)'], ['key' => 'Audit logging', 'val' => 'Full ward & theatre audit'], ['key' => 'Role separation', 'val' => 'Doctor · Nurse · Admin · Finance']]],
        ],
        'related' => ['opes-emr', 'opescare', 'rcmis'],
    ],

    'uhc-is' => [
        'slug' => 'uhc-is',
        'name' => 'UHC IS',
        'subtitle' => 'Universal Health Coverage Information System',
        'category' => 'Core Platform',
        'icon' => 'users',
        'color' => '#00C896',
        'tagline' => 'Manage government UHC beneficiaries, coverage schemes, and health facility reporting in one national-scale platform.',
        'description' => 'UHC IS is built for national and regional health authorities implementing Universal Health Coverage programmes. It manages beneficiary registration, coverage entitlements, facility claims verification, and population-level health reporting — providing governments, NGOs, and international donors with real-time visibility into programme effectiveness.',
        'description2' => 'Integrated with OPESCare Health ID, every UHC beneficiary is linked to their complete health record. Facilities report UHC services directly into the system; claims are validated automatically against registered entitlements before payment processing.',
        'target_users' => [
            'National and regional Ministries of Health',
            'Government UHC programme administrators',
            'International health funding bodies (WHO, World Bank, GAVI)',
            'NGOs managing community health programmes',
            'Social insurance funds (CNPS and equivalent)',
        ],
        'problems_solved' => [
            ['title' => 'No real-time visibility on UHC coverage uptake', 'desc' => 'Live dashboards show service utilisation, coverage gaps, and beneficiary activation rates.'],
            ['title' => 'Ghost beneficiaries and fraudulent claims', 'desc' => 'OPESCare Health ID verification eliminates duplicate beneficiary registrations and fake claims.'],
            ['title' => 'Manual facility reporting delays', 'desc' => 'Facilities submit UHC service data directly into the system — no paper forms, no postal delays.'],
            ['title' => 'No geographic coverage mapping', 'desc' => 'Heat maps show which districts are under-served and where programme expansion is needed.'],
        ],
        'stats' => [
            ['value' => 'National', 'label' => 'scale deployment'],
            ['value' => 'Real-time', 'label' => 'coverage dashboards'],
            ['value' => 'Auto', 'label' => 'claims validation'],
            ['value' => 'MoH', 'label' => 'reporting aligned'],
        ],
        'modules' => [
            ['icon' => 'users', 'name' => 'Beneficiary Registry', 'desc' => 'Register and manage UHC beneficiaries linked to OPESCare Health IDs with entitlement tracking.', 'features' => ['Bulk beneficiary import', 'Household & family linkage', 'Entitlement period management', 'OPESCare Health ID binding']],
            ['icon' => 'receipt', 'name' => 'Claims Management', 'desc' => 'Facility claims submitted electronically, validated against beneficiary entitlements, and tracked through payment.', 'features' => ['Electronic claims submission', 'Auto entitlement verification', 'Fraud detection flags', 'Payment status tracking']],
            ['icon' => 'bar-chart-2', 'name' => 'Coverage Analytics', 'desc' => 'Population dashboards showing service uptake, coverage gaps, and geographic distribution.', 'features' => ['Geographic coverage heat maps', 'Service utilisation by district', 'MoH HMIS integration', 'Donor reporting exports']],
        ],
        'workflow' => [
            ['step' => 'Enrolment', 'desc' => 'Beneficiary registered & Health ID linked'],
            ['step' => 'Service Use', 'desc' => 'Patient presents at facility'],
            ['step' => 'Claim Submitted', 'desc' => 'Facility logs service electronically'],
            ['step' => 'Auto-Validated', 'desc' => 'System verifies entitlement'],
            ['step' => 'Payment', 'desc' => 'Approved claim processed'],
        ],
        'benefits' => [
            ['icon' => 'eye', 'color' => '#00C896', 'title' => 'Real-time programme visibility', 'desc' => 'Governments and donors see live utilisation data — not quarterly paper reports.'],
            ['icon' => 'shield-check', 'color' => '#1A6FE8', 'title' => 'Fraud prevention built in', 'desc' => 'Health ID biometric verification eliminates ghost beneficiaries and duplicate claims.'],
            ['icon' => 'globe-2', 'color' => '#00C896', 'title' => 'National to district scale', 'desc' => 'Works at the national level while drilling down to individual facility and district reporting.'],
            ['icon' => 'landmark', 'color' => '#1A6FE8', 'title' => 'MoH & donor reporting', 'desc' => 'Pre-built report formats for Cameroon MoH, WHO, World Bank, and major donor agencies.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-hospital-his', 'rcmis'],
        'specs' => [
            ['group' => 'Scale', 'rows' => [['key' => 'Beneficiaries', 'val' => 'Millions (sharded architecture)'], ['key' => 'Facilities', 'val' => 'Unlimited facility endpoints'], ['key' => 'Claims throughput', 'val' => '10,000+ per day'], ['key' => 'Deployment', 'val' => 'Cloud (national) or Hybrid']]],
            ['group' => 'Interoperability', 'rows' => [['key' => 'Standard', 'val' => 'HL7 FHIR R4'], ['key' => 'Beneficiary ID', 'val' => 'OPESCare Health ID'], ['key' => 'Export', 'val' => 'CSV · Excel · DHIS2 · FHIR'], ['key' => 'API', 'val' => 'RESTful JSON']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'MFA · Biometric'], ['key' => 'Audit logging', 'val' => 'Every access & claim logged'], ['key' => 'Data residency', 'val' => 'In-country mandatory']]],
        ],
        'related' => ['opescare', 'opes-emr', 'rcmis'],
    ],

    'opes-triage' => [
        'slug' => 'opes-triage',
        'name' => 'Opes Triage',
        'subtitle' => 'Standalone Triage Management · Any Facility',
        'category' => 'Core Platform',
        'icon' => 'timer',
        'color' => '#00C896',
        'tagline' => 'Deploy standalone triage management in any hospital — even if you already have other software. Reduce wait times in days, not months.',
        'description' => 'Opes Triage is designed to solve one critical problem independently: patient wait times and triage chaos at the hospital entrance. Unlike other OPES systems, it can be deployed as a standalone product without replacing any existing software — making it the fastest way for any hospital to start its digital health journey.',
        'description2' => 'It implements a structured triage protocol (Manchester Triage System adapted for CEMAC facilities) and gives nurses, triage officers, and waiting room displays a real-time queue with colour-coded priority levels. When a facility is ready to expand, Opes Triage connects natively to OPES EMR and OPESCare Health ID.',
        'target_users' => [
            'Emergency departments of any size',
            'Hospitals with existing software that want to add triage',
            'District hospitals with high walk-in patient volumes',
            'Private clinics seeking faster patient processing',
            'Any facility starting its digital health journey',
        ],
        'problems_solved' => [
            ['title' => 'Patients waiting without priority assessment', 'desc' => 'Structured triage assigns severity levels so the sickest patients are always seen first.'],
            ['title' => 'No visibility on queue length and wait times', 'desc' => 'Real-time queue board shows every patient\'s position, priority, and estimated wait.'],
            ['title' => 'Replacement fear — existing software', 'desc' => 'Opes Triage runs alongside any existing HIS/EMR — no replacement required.'],
            ['title' => 'Triage data not captured for audit', 'desc' => 'Every triage decision is recorded with timestamp, nurse ID, and priority justification.'],
        ],
        'stats' => [
            ['value' => 'Standalone', 'label' => 'no EMR required'],
            ['value' => 'MTS', 'label' => 'triage protocol (adapted)'],
            ['value' => 'Days', 'label' => 'to deploy, not months'],
            ['value' => '↓ Wait', 'label' => 'times, measurably'],
        ],
        'modules' => [
            ['icon' => 'timer', 'name' => 'Triage Assessment', 'desc' => 'Structured triage protocol with vital signs capture and colour-coded priority assignment.', 'features' => ['Manchester Triage System (CEMAC adapted)', 'Vital signs at triage point', 'Chief complaint coding', 'Immediate / Urgent / Standard / Non-urgent / Deceased flags']],
            ['icon' => 'monitor', 'name' => 'Waiting Room Display', 'desc' => 'Large-screen queue board showing patient position, priority, and estimated wait time.', 'features' => ['Privacy-compliant display (ticket numbers)', 'Real-time queue updates', 'Multi-language display (EN/FR)', 'Average wait time counter']],
            ['icon' => 'bar-chart-2', 'name' => 'Triage Analytics', 'desc' => 'Department-level reporting on patient volumes, peak hours, triage accuracy, and wait times.', 'features' => ['Peak hour heatmaps', 'Priority distribution reports', 'Average triage-to-seen times', 'Nurse triage audit trails']],
        ],
        'workflow' => [
            ['step' => 'Patient Arrives', 'desc' => 'Walk-in or ambulance arrival logged'],
            ['step' => 'Vitals Taken', 'desc' => 'Nurse records BP, pulse, temp, SpO2'],
            ['step' => 'Priority Assigned', 'desc' => 'Colour-coded priority set per MTS'],
            ['step' => 'Queue Updated', 'desc' => 'Waiting room board updates live'],
            ['step' => 'Seen by Doctor', 'desc' => 'Patient called in priority order'],
        ],
        'benefits' => [
            ['icon' => 'zap', 'color' => '#00C896', 'title' => 'Deploy in days', 'desc' => 'No complex integration required. Opes Triage is running in your facility within days of purchase.'],
            ['icon' => 'shield-check', 'color' => '#1A6FE8', 'title' => 'Works with existing software', 'desc' => 'Runs alongside any HIS, EMR, or paper-based system. No replacement, no disruption.'],
            ['icon' => 'clock', 'color' => '#00C896', 'title' => 'Measurable wait time reduction', 'desc' => 'Priority-based queuing ensures the sickest patients are always treated first — and the data proves it.'],
            ['icon' => 'arrow-up-right', 'color' => '#1A6FE8', 'title' => 'Grows with you', 'desc' => 'When ready, connect Opes Triage directly to OPES EMR and OPESCare Health ID seamlessly.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-hospital-his'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Minimum server', 'val' => '2 vCPU, 4 GB RAM'], ['key' => 'Client', 'val' => 'Web browser (any device)'], ['key' => 'Display', 'val' => 'Any HDMI screen for queue board']]],
            ['group' => 'Integration', 'rows' => [['key' => 'Standalone', 'val' => 'Yes — no other system required'], ['key' => 'OPES EMR', 'val' => 'Optional native integration'], ['key' => 'OPESCare', 'val' => 'Optional Health ID lookup'], ['key' => 'API', 'val' => 'RESTful JSON (for custom HIS)']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'TLS 1.3 in transit'], ['key' => 'Authentication', 'val' => 'Role-based (Nurse / Admin)'], ['key' => 'Audit logging', 'val' => 'All triage decisions logged'], ['key' => 'Privacy', 'val' => 'Ticket number display (not names)']]],
        ],
        'related' => ['opes-emr', 'opescare', 'opes-hospital-his'],
    ],

    'opes-lab' => [
        'slug' => 'opes-lab',
        'name' => 'OPES Lab',
        'subtitle' => 'Laboratory Information System (LABIS)',
        'category' => 'Diagnostics',
        'icon' => 'microscope',
        'color' => '#1A6FE8',
        'tagline' => 'Complete laboratory management from order to validated result — integrated with OPES EMR and OPESCare in real time.',
        'description' => 'OPES Lab (LABIS) manages the complete laboratory workflow: from clinician test orders received directly from OPES EMR, through specimen collection, processing, quality control, and result validation, back to the patient record — automatically, with no manual transcription errors.',
        'description2' => 'It supports haematology, biochemistry, microbiology, serology, immunology, and parasitology workflows. Results are validated by the lab technician, then immediately available in the ordering clinician\'s OPES EMR record with abnormal values automatically flagged.',
        'target_users' => [
            'Hospital laboratory departments',
            'Standalone clinical laboratories and diagnostic centres',
            'Public health and reference laboratories',
            'NGO laboratory networks (e.g. TB, HIV programmes)',
            'Medical school teaching laboratories',
        ],
        'problems_solved' => [
            ['title' => 'Manual transcription errors in result reporting', 'desc' => 'Results flow electronically from the analyser to the patient record — zero manual entry.'],
            ['title' => 'Lost or delayed results reaching clinicians', 'desc' => 'Validated results appear in the EMR the moment the lab technician approves them.'],
            ['title' => 'No quality control tracking', 'desc' => 'Built-in QC protocols with Levey-Jennings charts and Westgard rules.'],
            ['title' => 'Reagent and consumable waste', 'desc' => 'Stock management module tracks reagent usage per test, flagging shortages before they cause service disruption.'],
        ],
        'stats' => [
            ['value' => '6+', 'label' => 'lab disciplines supported'],
            ['value' => 'Real-time', 'label' => 'result to EMR integration'],
            ['value' => 'QC', 'label' => 'built-in quality control'],
            ['value' => 'LIS', 'label' => 'analyser interface (HL7)'],
        ],
        'modules' => [
            ['icon' => 'clipboard-list', 'name' => 'Order Management', 'desc' => 'Receive and triage lab orders from OPES EMR or direct walk-in requests.', 'features' => ['Electronic order receipt from EMR', 'Walk-in specimen registration', 'Panel & individual test support', 'Priority (STAT vs routine) queuing']],
            ['icon' => 'flask-conical', 'name' => 'Specimen Processing', 'desc' => 'Track specimen collection, transport, receipt, and processing with barcode or QR labels.', 'features' => ['Barcode specimen labelling', 'Chain of custody tracking', 'Rejection criteria logging', 'Batch processing queues']],
            ['icon' => 'check-circle', 'name' => 'Result Validation', 'desc' => 'Two-tier validation (technician + pathologist) before results are released to the EMR.', 'features' => ['Reference range flags', 'Delta checks across visits', 'Critical value auto-alerts', 'Electronic authorisation']],
            ['icon' => 'bar-chart-2', 'name' => 'Quality Control', 'desc' => 'Built-in QC module with Levey-Jennings charts, Westgard rules, and audit trails.', 'features' => ['Levey-Jennings charts', 'Westgard rule violations', 'QC lot tracking', 'External QA programme support']],
        ],
        'workflow' => [
            ['step' => 'Order Received', 'desc' => 'From EMR or walk-in registration'],
            ['step' => 'Specimen Collected', 'desc' => 'Barcode label printed & attached'],
            ['step' => 'Processing', 'desc' => 'Specimen analysed in lab'],
            ['step' => 'QC Check', 'desc' => 'QC rules verified automatically'],
            ['step' => 'Validated', 'desc' => 'Technician / pathologist approves'],
            ['step' => 'Result Released', 'desc' => 'Appears instantly in OPES EMR'],
        ],
        'benefits' => [
            ['icon' => 'zap', 'color' => '#1A6FE8', 'title' => 'Zero transcription errors', 'desc' => 'Results flow electronically from analyser to patient record — no manual copying, no mistakes.'],
            ['icon' => 'clock', 'color' => '#00C896', 'title' => 'Faster turnaround times', 'desc' => 'Digital workflows cut average result turnaround time by 40% in typical deployments.'],
            ['icon' => 'shield-check', 'color' => '#1A6FE8', 'title' => 'Built-in quality control', 'desc' => 'Westgard rules and Levey-Jennings charts ensure result accuracy before any result is released.'],
            ['icon' => 'link', 'color' => '#00C896', 'title' => 'Real-time EMR integration', 'desc' => 'Results in the clinician\'s hands the moment the lab validates them — no phone calls, no faxes.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-hospital-his', 'radis'],
        'specs' => [
            ['group' => 'Analyser Interface', 'rows' => [['key' => 'Protocol', 'val' => 'HL7 v2 / ASTM E1381'], ['key' => 'Connection', 'val' => 'RS-232 · TCP/IP · USB'], ['key' => 'Disciplines', 'val' => 'Haematology · Biochemistry · Micro · Serology'], ['key' => 'Manual entry', 'val' => 'Supported for non-interfaced tests']]],
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Minimum server', 'val' => '4 vCPU, 8 GB RAM'], ['key' => 'Offline mode', 'val' => 'Partial (local processing)'], ['key' => 'Database', 'val' => 'MySQL 8 / PostgreSQL 15']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'Role-based (Tech / Pathologist / Admin)'], ['key' => 'Audit logging', 'val' => 'All validations & releases logged'], ['key' => 'Result traceability', 'val' => 'Full chain of custody']]],
        ],
        'related' => ['opes-emr', 'pharmis', 'radis'],
    ],

    'pharmis' => [
        'slug' => 'pharmis',
        'name' => 'PHARMIS',
        'subtitle' => 'Pharmacy Information System',
        'category' => 'Diagnostics',
        'icon' => 'pill',
        'color' => '#1A6FE8',
        'tagline' => 'Hospital and retail pharmacy management — from prescription receipt to dispensing, stock control, and procurement.',
        'description' => 'PHARMIS is a complete pharmacy information system covering inpatient dispensing, outpatient pharmacy, and retail pharmacy workflows. It receives electronic prescriptions directly from OPES EMR with drug-interaction and allergy alerts already checked, and guides the pharmacist through dispensing, counselling, and patient education.',
        'description2' => 'The stock management module tracks every medicine from receipt to dispensing with batch and expiry date control, automated reorder alerts, and supplier management. PHARMIS integrates with RCMIS for automated billing of every item dispensed.',
        'target_users' => [
            'Hospital inpatient and outpatient pharmacies',
            'Standalone retail pharmacies and dispensaries',
            'Community health centre drug stores',
            'Government essential medicines stores',
            'NGO programme pharmacies (ARV, TB, malaria)',
        ],
        'problems_solved' => [
            ['title' => 'Medication errors from handwritten prescriptions', 'desc' => 'Electronic prescriptions from OPES EMR arrive pre-typed with drug, dose, frequency, and route.'],
            ['title' => 'Drug stockouts and expiry wastage', 'desc' => 'Automated reorder alerts and FEFO stock rotation prevent stockouts and expired medicine wastage.'],
            ['title' => 'Pharmacist unaware of patient allergies', 'desc' => 'Allergy and interaction alerts from the patient\'s OPESCare record are visible at the dispensing screen.'],
            ['title' => 'No audit trail on controlled substances', 'desc' => 'Every controlled substance dispensing is logged with pharmacist ID, quantity, and patient details.'],
        ],
        'stats' => [
            ['value' => 'ePrescription', 'label' => 'from OPES EMR'],
            ['value' => 'FEFO', 'label' => 'stock rotation'],
            ['value' => 'Auto', 'label' => 'reorder alerts'],
            ['value' => 'Controlled', 'label' => 'substance audit'],
        ],
        'modules' => [
            ['icon' => 'pill', 'name' => 'Dispensing', 'desc' => 'Process electronic and manual prescriptions with drug, dose, and counselling prompts.', 'features' => ['Electronic prescription receipt', 'Barcode scanning', 'Patient counselling notes', 'Label printing']],
            ['icon' => 'package', 'name' => 'Stock Management', 'desc' => 'Manage medicines from receipt through dispensing with batch and expiry control.', 'features' => ['Batch & expiry tracking', 'FEFO dispensing', 'Automated reorder alerts', 'Supplier & GRN management']],
            ['icon' => 'receipt', 'name' => 'Billing Integration', 'desc' => 'Every item dispensed is automatically posted to RCMIS for patient invoicing.', 'features' => ['Auto-post to RCMIS', 'Insurance claim tagging', 'CNPS tariff schedules', 'Cash & credit dispensing']],
        ],
        'workflow' => [
            ['step' => 'Prescription', 'desc' => 'Received from OPES EMR electronically'],
            ['step' => 'DUR Check', 'desc' => 'Drug-interaction & allergy verification'],
            ['step' => 'Dispensed', 'desc' => 'Pharmacist picks & labels items'],
            ['step' => 'Counselled', 'desc' => 'Patient education recorded'],
            ['step' => 'Billed', 'desc' => 'Auto-posted to RCMIS invoice'],
        ],
        'benefits' => [
            ['icon' => 'shield-check', 'color' => '#1A6FE8', 'title' => 'Safer dispensing', 'desc' => 'Drug-interaction and allergy checks run automatically on every prescription before dispensing.'],
            ['icon' => 'package', 'color' => '#00C896', 'title' => 'No more stockouts', 'desc' => 'Automated reorder alerts and FEFO rotation keep the pharmacy stocked and wastage minimal.'],
            ['icon' => 'link', 'color' => '#1A6FE8', 'title' => 'EMR-connected', 'desc' => 'Electronic prescriptions from OPES EMR arrive instantly — no transcription, no lost paper Rx.'],
            ['icon' => 'receipt', 'color' => '#00C896', 'title' => 'Auto-billing', 'desc' => 'Every dispensed item posts automatically to the patient\'s RCMIS invoice — zero billing leakage.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-hospital-his', 'rcmis'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Minimum server', 'val' => '2 vCPU, 4 GB RAM'], ['key' => 'Offline mode', 'val' => 'Supported (local cache)'], ['key' => 'Barcode', 'val' => 'EAN-13 · Code 128 support']]],
            ['group' => 'Integration', 'rows' => [['key' => 'Prescription', 'val' => 'HL7 FHIR MedicationRequest'], ['key' => 'Stock standard', 'val' => 'GS1 medicine codes'], ['key' => 'Billing', 'val' => 'RCMIS auto-post'], ['key' => 'API', 'val' => 'RESTful JSON']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'Role-based (Pharmacist / Tech / Admin)'], ['key' => 'Controlled substances', 'val' => 'Full dispensing audit trail'], ['key' => 'Narcotics register', 'val' => 'Electronic register output']]],
        ],
        'related' => ['opes-emr', 'opes-lab', 'rcmis'],
    ],

    'radis' => [
        'slug' => 'radis',
        'name' => 'RADIS',
        'subtitle' => 'Radiology Information System',
        'category' => 'Diagnostics',
        'icon' => 'image-up',
        'color' => '#1A6FE8',
        'tagline' => 'Manage radiology orders, DICOM images, and radiologist reports — integrated directly with OPES EMR patient records.',
        'description' => 'RADIS manages the complete radiology department workflow: imaging requests from OPES EMR arrive electronically, are scheduled on the modality worklist, processed, and the radiologist\'s validated report is returned to the patient record automatically. DICOM images are archived and viewable within the EMR.',
        'description2' => 'RADIS supports X-ray, ultrasound, CT, and MRI workflows. A built-in DICOM viewer means clinicians can view images directly in the patient\'s EMR record without needing a separate workstation — critical in low-resource settings.',
        'target_users' => [
            'Hospital radiology departments',
            'Standalone diagnostic imaging centres',
            'Ultrasound and X-ray units in community hospitals',
            'Teleradiology services covering rural facilities',
            'Teaching hospitals with radiology training programmes',
        ],
        'problems_solved' => [
            ['title' => 'Imaging requests lost or delayed', 'desc' => 'Electronic orders from OPES EMR arrive on the radiology worklist instantly — no paper forms.'],
            ['title' => 'Reports not reaching clinicians', 'desc' => 'Validated radiology reports return to the patient\'s EMR record the moment the radiologist approves.'],
            ['title' => 'No image archive — films lost or degraded', 'desc' => 'DICOM PACS archive stores every image permanently, accessible from any authorised workstation.'],
            ['title' => 'No rural access to radiologist expertise', 'desc' => 'Teleradiology module enables remote reporting for facilities without on-site radiologists.'],
        ],
        'stats' => [
            ['value' => 'DICOM', 'label' => 'image archive (PACS)'],
            ['value' => 'Real-time', 'label' => 'report to EMR'],
            ['value' => 'Tele', 'label' => 'radiology module'],
            ['value' => 'X-ray · CT · MRI · US', 'label' => 'modalities'],
        ],
        'modules' => [
            ['icon' => 'image-up', 'name' => 'Modality Worklist', 'desc' => 'Electronic imaging orders scheduled on the modality worklist with patient and study details.', 'features' => ['DICOM MWL integration', 'Scheduler & slot management', 'STAT vs routine priority', 'Multi-modality support']],
            ['icon' => 'monitor', 'name' => 'DICOM Viewer', 'desc' => 'Web-based DICOM viewer embedded in the EMR for clinician image review without extra software.', 'features' => ['In-browser DICOM display', 'Window/level & zoom tools', 'Measurement annotations', 'Multi-series comparison']],
            ['icon' => 'file-text', 'name' => 'Reporting & Validation', 'desc' => 'Structured radiology reporting with voice dictation and radiologist electronic sign-off.', 'features' => ['Structured report templates', 'Voice dictation support', 'Two-tier validation', 'Auto-release to OPES EMR']],
        ],
        'workflow' => [
            ['step' => 'Order Received', 'desc' => 'From OPES EMR electronically'],
            ['step' => 'Scheduled', 'desc' => 'Patient booked on worklist'],
            ['step' => 'Imaging Done', 'desc' => 'Images acquired & archived'],
            ['step' => 'Reported', 'desc' => 'Radiologist writes & signs report'],
            ['step' => 'Released', 'desc' => 'Report & images in OPES EMR'],
        ],
        'benefits' => [
            ['icon' => 'image-up', 'color' => '#1A6FE8', 'title' => 'Permanent image archive', 'desc' => 'Every DICOM image stored permanently — no lost films, no degraded X-rays.'],
            ['icon' => 'clock', 'color' => '#00C896', 'title' => 'Faster report turnaround', 'desc' => 'Digital workflow cuts average reporting time from days to hours.'],
            ['icon' => 'link', 'color' => '#1A6FE8', 'title' => 'In-EMR image viewing', 'desc' => 'Clinicians view images in the patient record — no separate PACS workstation needed.'],
            ['icon' => 'globe-2', 'color' => '#00C896', 'title' => 'Teleradiology support', 'desc' => 'Remote radiologists can report for rural facilities without on-site specialist coverage.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-hospital-his', 'opes-lab'],
        'specs' => [
            ['group' => 'Imaging', 'rows' => [['key' => 'Standard', 'val' => 'DICOM 3.0'], ['key' => 'Modalities', 'val' => 'X-ray · CT · MRI · Ultrasound · Fluoroscopy'], ['key' => 'Worklist', 'val' => 'DICOM MWL (C-FIND)'], ['key' => 'Storage', 'val' => 'PACS (local or cloud S3)']]],
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud PACS'], ['key' => 'Minimum server', 'val' => '8 vCPU, 32 GB RAM, SSD storage'], ['key' => 'Viewer', 'val' => 'Web browser (zero install)'], ['key' => 'Archive', 'val' => 'Configurable retention period']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'Role-based (Radiographer / Radiologist / Clinician)'], ['key' => 'Audit logging', 'val' => 'Every image access logged'], ['key' => 'DICOM anonymisation', 'val' => 'For teaching & teleradiology']]],
        ],
        'related' => ['opes-lab', 'opes-emr', 'opes-hospital-his'],
    ],

    'opes-cdms' => [
        'slug' => 'opes-cdms',
        'name' => 'OPES CDMS',
        'subtitle' => 'Clinical Document Management System',
        'category' => 'Administration & Finance',
        'icon' => 'folder-open',
        'color' => '#64748b',
        'tagline' => 'Capture, store, and retrieve every clinical document — scanned paper records, discharge letters, consent forms, referral letters, and more.',
        'description' => 'OPES CDMS is the digital document repository for clinical records. It enables facilities to scan and index paper records, store structured and unstructured clinical documents, and retrieve any document instantly by patient Health ID, document type, or date — even for pre-digital patient histories.',
        'description2' => 'Documents stored in OPES CDMS are accessible directly within OPES EMR and OPES Hospital HIS, giving clinicians a complete view of the patient\'s record including scanned historical documents that predate the digital system.',
        'target_users' => [
            'Facilities transitioning from paper to digital records',
            'Medical records departments managing large document volumes',
            'Hospital legal teams storing consent and medicolegal documents',
            'Facilities with legacy paper records requiring digitisation',
            'Any OPES EMR or Hospital HIS deployment',
        ],
        'problems_solved' => [
            ['title' => 'Physical records lost, misfiled, or destroyed', 'desc' => 'Every document stored digitally in a permanent, searchable archive.'],
            ['title' => 'Clinicians cannot find old records at point of care', 'desc' => 'Instant retrieval by patient Health ID from within OPES EMR.'],
            ['title' => 'Storage space consumed by paper records', 'desc' => 'Digitisation programme eliminates physical storage needs over time.'],
        ],
        'stats' => [
            ['value' => 'Unlimited', 'label' => 'document storage'],
            ['value' => 'Instant', 'label' => 'retrieval by Health ID'],
            ['value' => 'OCR', 'label' => 'scanned text search'],
            ['value' => 'EN/FR', 'label' => 'bilingual interface'],
        ],
        'modules' => [
            ['icon' => 'scan', 'name' => 'Document Capture', 'desc' => 'High-speed scanning with automatic indexing by patient Health ID and document type.', 'features' => ['Batch scanning support', 'QR & barcode auto-index', 'OCR text extraction', 'Mobile photo capture']],
            ['icon' => 'search', 'name' => 'Document Retrieval', 'desc' => 'Instant search by patient, document type, date range, or full-text OCR content.', 'features' => ['Patient Health ID lookup', 'Document type filtering', 'Full-text search (OCR)', 'In-EMR document panel']],
        ],
        'workflow' => [
            ['step' => 'Document Created', 'desc' => 'Scanned, uploaded, or generated'],
            ['step' => 'Indexed', 'desc' => 'Patient ID & type tagged automatically'],
            ['step' => 'Stored', 'desc' => 'Encrypted in document archive'],
            ['step' => 'Retrieved', 'desc' => 'Instant lookup from EMR or search'],
        ],
        'benefits' => [
            ['icon' => 'folder-open', 'color' => '#64748b', 'title' => 'Complete patient history', 'desc' => 'Paper and digital records in one place — pre-digital history visible alongside current digital records.'],
            ['icon' => 'search', 'color' => '#64748b', 'title' => 'Instant retrieval', 'desc' => 'Any document, any patient, found in seconds by Health ID — from any authorised terminal.'],
            ['icon' => 'shield-check', 'color' => '#64748b', 'title' => 'Medicolegal compliance', 'desc' => 'Consent forms, referral letters, and discharge summaries stored with full audit trail.'],
            ['icon' => 'hard-drive', 'color' => '#64748b', 'title' => 'No physical storage costs', 'desc' => 'Digitisation eliminates the cost and risk of paper record storage over time.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-hospital-his'],
        'specs' => [
            ['group' => 'Storage', 'rows' => [['key' => 'Formats', 'val' => 'PDF · JPEG · PNG · DICOM · HL7 CDA'], ['key' => 'Archive', 'val' => 'Local NAS or cloud (S3-compatible)'], ['key' => 'Retention', 'val' => 'Configurable (minimum 15 years)'], ['key' => 'OCR', 'val' => 'English & French']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Access control', 'val' => 'Role-based per document type'], ['key' => 'Audit logging', 'val' => 'Every view, edit & download logged'], ['key' => 'Deletion', 'val' => 'Requires dual authorisation']]],
        ],
        'related' => ['opes-emr', 'opes-hospital-his', 'rcmis'],
    ],

    'rcmis' => [
        'slug' => 'rcmis',
        'name' => 'RCMIS',
        'subtitle' => 'Revenue Cycle Management Information System',
        'category' => 'Administration & Finance',
        'icon' => 'receipt',
        'color' => '#64748b',
        'tagline' => 'Automate billing, insurance claims, CNPS submissions, and revenue reporting across your entire facility.',
        'description' => 'RCMIS is the financial backbone of OPES-connected facilities. It receives billable acts automatically from OPES EMR, OPES Lab, PHARMIS, and RADIS — building a complete, accurate patient invoice without any manual data entry by the billing team. Every consultation, lab test, dispensed medicine, and imaging study is captured.',
        'description2' => 'Insurance claims, CNPS submissions, and mutual fund reimbursement requests are generated automatically from the same billing data and tracked through to payment. Revenue dashboards give finance directors real-time visibility on collections, outstanding claims, and payer mix.',
        'target_users' => [
            'Hospital finance and billing departments',
            'Private clinic owners and administrators',
            'Multi-facility groups managing consolidated revenue reporting',
            'Insurance claims processing teams',
            'CNPS-affiliated healthcare providers',
        ],
        'problems_solved' => [
            ['title' => 'Billable acts missed due to paper-based billing', 'desc' => 'Every clinical act from every OPES system posts automatically — zero billing leakage.'],
            ['title' => 'Insurance claim rejections from incomplete data', 'desc' => 'Claims are built from validated clinical data with all required fields pre-populated.'],
            ['title' => 'No visibility on outstanding payments', 'desc' => 'Real-time aging reports show every unpaid invoice by payer, age, and amount.'],
            ['title' => 'Manual CNPS submission errors', 'desc' => 'CNPS-format claims generated automatically from the billing data with correct tariff codes.'],
        ],
        'stats' => [
            ['value' => 'Zero', 'label' => 'billing leakage'],
            ['value' => 'Auto', 'label' => 'invoice from clinical acts'],
            ['value' => 'CNPS', 'label' => 'claim generation'],
            ['value' => 'Real-time', 'label' => 'revenue dashboards'],
        ],
        'modules' => [
            ['icon' => 'receipt', 'name' => 'Automated Invoicing', 'desc' => 'Patient invoices built automatically from all clinical acts across every connected OPES system.', 'features' => ['Auto-receive from EMR, Lab, Pharmacy, Radiology', 'Tariff schedule management', 'Multi-currency support', 'Printed & electronic invoice']],
            ['icon' => 'file-check', 'name' => 'Insurance & CNPS Claims', 'desc' => 'Insurance claims and CNPS submissions generated automatically and tracked to payment.', 'features' => ['CNPS tariff code mapping', 'Electronic claim submission', 'Rejection & re-submission workflow', 'Payer payment tracking']],
            ['icon' => 'trending-up', 'name' => 'Revenue Analytics', 'desc' => 'Real-time dashboards on collections, outstanding, payer mix, and revenue by department.', 'features' => ['Daily collections report', 'Aging accounts receivable', 'Payer mix analysis', 'Department revenue breakdown']],
        ],
        'workflow' => [
            ['step' => 'Clinical Act', 'desc' => 'Service performed in any OPES system'],
            ['step' => 'Auto-Posted', 'desc' => 'Act logged to patient invoice instantly'],
            ['step' => 'Invoice Built', 'desc' => 'Complete bill ready at discharge'],
            ['step' => 'Claim Generated', 'desc' => 'Insurance / CNPS claim auto-built'],
            ['step' => 'Payment Tracked', 'desc' => 'Collections tracked to zero balance'],
        ],
        'benefits' => [
            ['icon' => 'trending-up', 'color' => '#64748b', 'title' => 'Zero billing leakage', 'desc' => 'Every clinical act from every OPES system is captured automatically — nothing falls through the cracks.'],
            ['icon' => 'clock', 'color' => '#64748b', 'title' => 'Faster claims processing', 'desc' => 'Insurance claims are built and submitted electronically — no manual form-filling.'],
            ['icon' => 'eye', 'color' => '#64748b', 'title' => 'Real-time financial visibility', 'desc' => 'Finance directors see collections, outstanding, and payer mix in real time — not at month end.'],
            ['icon' => 'shield-check', 'color' => '#64748b', 'title' => 'CNPS compliance', 'desc' => 'CNPS tariff schedules built in — correct codes applied automatically on every claim.'],
        ],
        'integrations' => ['opes-emr', 'opes-hospital-his', 'opes-lab', 'pharmis', 'radis', 'uhc-is'],
        'specs' => [
            ['group' => 'Billing', 'rows' => [['key' => 'Tariff systems', 'val' => 'CNPS · Mutual funds · Private insurance · Cash'], ['key' => 'Multi-payer', 'val' => 'Split billing per visit'], ['key' => 'Currency', 'val' => 'XAF (FCFA) primary · Multi-currency'], ['key' => 'VAT / tax', 'val' => 'Configurable rate schedules']]],
            ['group' => 'Integration', 'rows' => [['key' => 'Receive from', 'val' => 'OPES EMR · Lab · Pharmacy · Radiology'], ['key' => 'Claims format', 'val' => 'CNPS electronic format'], ['key' => 'Export', 'val' => 'CSV · Excel · PDF reports'], ['key' => 'Accounting', 'val' => 'Sage / QuickBooks export']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Authentication', 'val' => 'Role-based (Cashier / Billing / Finance Director)'], ['key' => 'Audit logging', 'val' => 'Every billing action logged & timestamped'], ['key' => 'Void control', 'val' => 'Dual authorisation for invoice voids']]],
        ],
        'related' => ['opes-emr', 'pharmis', 'opes-hospital-his'],
    ],

];
