<?php

// Specialist product definitions — merged into products.php at runtime via ProductRepository
// Each entry follows the same schema as config/products.php

return [

    'cardis' => [
        'slug' => 'cardis', 'name' => 'CARDIS', 'subtitle' => 'Cardiology Information System',
        'category' => 'Specialist Systems', 'icon' => 'heart-pulse', 'color' => '#94a3b8',
        'tagline' => 'Dedicated cardiology workflows — ECG, echo reports, cardiac catheterisation, and long-term cardiovascular risk management.',
        'description' => 'CARDIS is a specialist system for cardiology units and cardiac centres. It provides structured clinical workflows for ECG interpretation, echocardiography reporting, cardiac catheterisation records, and long-term cardiovascular risk factor tracking — integrated with OPES EMR so the cardiologist always sees the full patient history.',
        'description2' => 'Every CARDIS record is linked to the patient\'s OPESCare Health ID, enabling cardiologists to see medications from PHARMIS, lab results from OPES Lab (lipids, troponins, BNP), and referral history from OPES EMR in a single screen.',
        'target_users' => ['Cardiac centres and cardiology units', 'General hospitals with cardiology departments', 'Private cardiologist practices', 'Rehabilitation centres with cardiac programmes', 'Telemedicine cardiology services'],
        'problems_solved' => [
            ['title' => 'ECG and echo reports not linked to the patient record', 'desc' => 'CARDIS stores every ECG trace and echo report against the OPESCare Health ID.'],
            ['title' => 'Cardiovascular risk factors not tracked over time', 'desc' => 'Longitudinal risk factor dashboards show BP, lipids, BMI, HbA1c, and smoking trends across all visits.'],
            ['title' => 'Cardiac medications not visible to other clinicians', 'desc' => 'All CARDIS prescriptions feed into PHARMIS and are visible in OPES EMR.'],
        ],
        'stats' => [['value' => 'ECG', 'label' => 'integration & reporting'], ['value' => 'Echo', 'label' => 'structured reports'], ['value' => 'Risk', 'label' => 'factor tracking'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'heart-pulse', 'name' => 'ECG Management', 'desc' => 'Record, store, and report 12-lead ECG studies.', 'features' => ['Digital ECG import', 'Structured interpretation templates', 'Comparison across visits', 'Auto-alert for critical findings']],
            ['icon' => 'activity', 'name' => 'Echocardiography Reporting', 'desc' => 'Structured echo reports with standard measurements and valve assessment.', 'features' => ['ASE/EACVI measurement templates', 'M-mode & Doppler fields', 'Image annotation', 'Report to OPES EMR']],
            ['icon' => 'trending-up', 'name' => 'Cardiovascular Risk', 'desc' => 'Track risk factors longitudinally with Framingham and ESC risk scoring.', 'features' => ['BP · lipids · BMI · HbA1c trends', 'Framingham / ESC risk scores', 'Lifestyle intervention logs', 'Target achievement tracking']],
        ],
        'workflow' => [['step' => 'Referral', 'desc' => 'From OPES EMR to CARDIS'], ['step' => 'Assessment', 'desc' => 'ECG, echo, history review'], ['step' => 'Report', 'desc' => 'Structured report validated'], ['step' => 'Plan', 'desc' => 'Medications & follow-up'], ['step' => 'Back to EMR', 'desc' => 'Report visible in OPES EMR']],
        'benefits' => [
            ['icon' => 'heart-pulse', 'color' => '#94a3b8', 'title' => 'Structured cardiac documentation', 'desc' => 'ECG and echo reports follow international standards — every field captured consistently.'],
            ['icon' => 'trending-up', 'color' => '#94a3b8', 'title' => 'Risk factor longitudinal view', 'desc' => 'Track every cardiovascular risk factor from first visit to current — in one dashboard.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Full EMR integration', 'desc' => 'Cardiac results and plans visible to every clinician via OPES EMR and OPESCare Health ID.'],
            ['icon' => 'languages', 'color' => '#94a3b8', 'title' => 'Bilingual by design', 'desc' => 'All reports and interfaces in English and French — suitable for bilingual cardiology teams.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-lab', 'pharmis', 'radis'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Minimum server', 'val' => '4 vCPU, 8 GB RAM'], ['key' => 'ECG device interface', 'val' => 'HL7 aECG / SCP-ECG'], ['key' => 'Offline mode', 'val' => 'Partial']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 · TLS 1.3'], ['key' => 'Authentication', 'val' => 'Role-based (Cardiologist / Tech / Admin)'], ['key' => 'Audit logging', 'val' => 'Full access & report trail'], ['key' => 'Languages', 'val' => 'English · French']]],
        ],
        'related' => ['opes-emr', 'opes-lab', 'rehabis'],
    ],

    'dentis' => [
        'slug' => 'dentis', 'name' => 'DENTIS', 'subtitle' => 'Dental Information System',
        'category' => 'Specialist Systems', 'icon' => 'scan-face', 'color' => '#94a3b8',
        'tagline' => 'Complete dental practice management — charting, treatment planning, imaging, and billing for clinics of any size.',
        'description' => 'DENTIS provides a complete dental information system covering patient registration, dental charting (FDI notation), treatment planning, procedure records, dental X-ray image management, and integrated billing through RCMIS. It serves standalone dental clinics, polyclinic dental units, and hospital dental departments.',
        'description2' => 'Patient records are linked to OPESCare Health ID, so dental clinicians can see the patient\'s systemic medications (relevant to anaesthesia and antibiotic prescribing), medical history, and allergies from OPES EMR before any procedure.',
        'target_users' => ['Standalone dental clinics', 'Polyclinic dental units', 'Hospital dental departments', 'Dental schools and teaching clinics', 'Orthodontic and maxillofacial surgery centres'],
        'problems_solved' => [
            ['title' => 'Paper dental charts lost or illegible', 'desc' => 'Digital FDI tooth chart with colour-coded conditions is always accurate and instantly accessible.'],
            ['title' => 'Medical history not visible at dental chair', 'desc' => 'Systemic conditions, allergies, and medications visible via OPESCare Health ID link.'],
            ['title' => 'Dental billing complex and error-prone', 'desc' => 'Procedure-based billing auto-posts to RCMIS with correct tariff codes.'],
        ],
        'stats' => [['value' => 'FDI', 'label' => 'tooth notation'], ['value' => 'X-ray', 'label' => 'image management'], ['value' => 'Treatment', 'label' => 'planning module'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'scan-face', 'name' => 'Dental Charting', 'desc' => 'Interactive FDI tooth chart with condition coding, treatment recording, and historical views.', 'features' => ['FDI / Universal notation', 'Colour-coded condition map', 'Perio charting (BPE/CPITN)', 'Historical chart comparison']],
            ['icon' => 'image-up', 'name' => 'Dental Imaging', 'desc' => 'Intraoral and panoramic X-ray image management with annotation tools.', 'features' => ['DICOM support', 'Intraoral sensor interface', 'OPG / CBCT archiving', 'Before/after comparison']],
            ['icon' => 'clipboard-list', 'name' => 'Treatment Planning', 'desc' => 'Multi-visit treatment plans with cost estimates, consent recording, and scheduling.', 'features' => ['Multi-phase treatment plans', 'Estimated cost breakdown', 'Patient consent recording', 'Appointment booking link']],
        ],
        'workflow' => [['step' => 'Registration', 'desc' => 'Patient & medical history'], ['step' => 'Examination', 'desc' => 'Chart updated, X-rays taken'], ['step' => 'Diagnosis', 'desc' => 'Conditions coded on chart'], ['step' => 'Treatment Plan', 'desc' => 'Plan created & consented'], ['step' => 'Procedure', 'desc' => 'Recorded & billed to RCMIS']],
        'benefits' => [
            ['icon' => 'scan-face', 'color' => '#94a3b8', 'title' => 'Digital charting', 'desc' => 'FDI tooth chart eliminates paper charts — always accurate, always available.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Medical history at the chair', 'desc' => 'Systemic conditions and allergies from OPES EMR visible before any procedure.'],
            ['icon' => 'receipt', 'color' => '#94a3b8', 'title' => 'Automated billing', 'desc' => 'Dental procedures auto-posted to RCMIS with correct dental tariff codes.'],
            ['icon' => 'calendar', 'color' => '#94a3b8', 'title' => 'Multi-visit planning', 'desc' => 'Complex treatment plans tracked across multiple appointments with consent recorded.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'rcmis', 'pharmis'],
        'specs' => [
            ['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Minimum server', 'val' => '2 vCPU, 4 GB RAM'], ['key' => 'Imaging', 'val' => 'DICOM (intraoral & OPG)'], ['key' => 'Offline mode', 'val' => 'Supported']]],
            ['group' => 'Security', 'rows' => [['key' => 'Encryption', 'val' => 'AES-256 · TLS 1.3'], ['key' => 'Authentication', 'val' => 'Role-based (Dentist / Nurse / Receptionist)'], ['key' => 'Languages', 'val' => 'English · French']]],
        ],
        'related' => ['opes-emr', 'rcmis', 'ophis'],
    ],

    'dermis' => [
        'slug' => 'dermis', 'name' => 'DERMIS', 'subtitle' => 'Dermatology Information System',
        'category' => 'Specialist Systems', 'icon' => 'layers', 'color' => '#94a3b8',
        'tagline' => 'Dermatology clinical records with lesion photography, dermoscopy image management, and structured diagnosis coding.',
        'description' => 'DERMIS provides specialist clinical tools for dermatology departments: structured skin condition documentation, lesion photography with size and location mapping on a body diagram, dermoscopy image management, and ICD-10 coded diagnoses for common dermatological conditions prevalent in CEMAC populations.',
        'description2' => 'Connected to PHARMIS for topical and systemic prescription management, and to OPES Lab for dermatological investigations (skin biopsies, cultures, allergy patch tests), DERMIS gives dermatologists a complete specialist workflow.',
        'target_users' => ['Hospital dermatology departments', 'Private dermatology clinics', 'Skin disease research centres', 'Leprosy and infectious skin disease programmes', 'Aesthetic medicine clinics'],
        'problems_solved' => [
            ['title' => 'Lesion changes not tracked photographically over time', 'desc' => 'Standardised lesion photography with body location mapping and longitudinal comparison.'],
            ['title' => 'Dermatological diagnoses not coded for HMIS', 'desc' => 'ICD-10 coded diagnoses feed directly into HMIS reporting for skin disease surveillance.'],
        ],
        'stats' => [['value' => 'Lesion', 'label' => 'photo management'], ['value' => 'ICD-10', 'label' => 'derma codes'], ['value' => 'Dermoscopy', 'label' => 'image support'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'layers', 'name' => 'Skin Examination', 'desc' => 'Structured skin assessment with body diagram, lesion mapping, and photography.', 'features' => ['Interactive body diagram', 'Lesion measurement & photo', 'Dermoscopy image import', 'Longitudinal lesion comparison']],
            ['icon' => 'flask-conical', 'name' => 'Investigation Orders', 'desc' => 'Order skin biopsies, cultures, KOH preparations, and patch tests directly from the consultation.', 'features' => ['Biopsy request to Lab', 'Patch test scheduling', 'Result auto-return from OPES Lab', 'Histology report filing']],
        ],
        'workflow' => [['step' => 'Referral', 'desc' => 'From OPES EMR or walk-in'], ['step' => 'Examination', 'desc' => 'Skin assessment & photography'], ['step' => 'Diagnosis', 'desc' => 'ICD-10 coded'], ['step' => 'Treatment', 'desc' => 'Prescription via PHARMIS'], ['step' => 'Follow-up', 'desc' => 'Lesion comparison over time']],
        'benefits' => [
            ['icon' => 'layers', 'color' => '#94a3b8', 'title' => 'Visual lesion tracking', 'desc' => 'Standardised photography and body mapping track lesion changes objectively over time.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Full ecosystem integration', 'desc' => 'Lab, pharmacy, and patient history all accessible in the same dermatology consultation screen.'],
            ['icon' => 'bar-chart-2', 'color' => '#94a3b8', 'title' => 'Disease surveillance ready', 'desc' => 'ICD-10 coded diagnoses feed directly into MoH HMIS skin disease reporting.'],
            ['icon' => 'languages', 'color' => '#94a3b8', 'title' => 'Bilingual', 'desc' => 'Full English and French interface for CEMAC dermatology teams.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-lab', 'pharmis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Imaging', 'val' => 'JPEG / PNG / DICOM'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['opes-emr', 'opes-lab', 'pharmis'],
    ],

    'endois' => [
        'slug' => 'endois', 'name' => 'ENDOIS', 'subtitle' => 'Endocrinology & Diabetes Information System',
        'category' => 'Specialist Systems', 'icon' => 'gauge', 'color' => '#94a3b8',
        'tagline' => 'Specialist management of diabetes, thyroid disease, and endocrine disorders — with longitudinal metabolic tracking and patient education tools.',
        'description' => 'ENDOIS is designed for endocrinology departments and diabetes clinics managing patients with chronic metabolic conditions. It provides structured workflows for diabetes management (Type 1, Type 2, gestational), thyroid disease, adrenal disorders, and other endocrine conditions — all with longitudinal tracking dashboards critical for chronic disease management.',
        'description2' => 'Deep integration with OPES Lab enables automatic import of HbA1c, fasting glucose, lipids, thyroid function tests, and other endocrine markers directly into the patient\'s longitudinal trend dashboard — giving clinicians an instant view of disease control over time.',
        'target_users' => ['Endocrinology departments in hospitals', 'Diabetes clinics and diabetology centres', 'Internal medicine departments', 'Community diabetes prevention programmes', 'WHO / NGO non-communicable disease programmes'],
        'problems_solved' => [
            ['title' => 'No longitudinal view of glycaemic control', 'desc' => 'HbA1c, fasting glucose, and self-monitoring records tracked on one dashboard across all visits.'],
            ['title' => 'Diabetes complications not systematically screened', 'desc' => 'Complication screening checklists (feet, eyes, kidneys, cardiovascular) embedded in every annual review.'],
            ['title' => 'Insulin and medication changes not tracked', 'desc' => 'Every dose adjustment recorded with date and reason — full medication history at a glance.'],
        ],
        'stats' => [['value' => 'HbA1c', 'label' => 'longitudinal tracking'], ['value' => 'Complication', 'label' => 'screening checklists'], ['value' => 'NCD', 'label' => 'programme ready'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'gauge', 'name' => 'Diabetes Management', 'desc' => 'Complete diabetes workflow with glycaemic tracking, complication screening, and education.', 'features' => ['HbA1c & glucose trend dashboard', 'Complication screening checklists', 'Insulin dose & adjustment log', 'Patient self-monitoring import']],
            ['icon' => 'activity', 'name' => 'Endocrine Disorders', 'desc' => 'Structured clinical records for thyroid, adrenal, pituitary, and other endocrine conditions.', 'features' => ['Thyroid function trend tracking', 'Hormone replacement therapy logs', 'Adrenal crisis protocol prompts', 'Growth & puberty assessment charts']],
        ],
        'workflow' => [['step' => 'Diagnosis', 'desc' => 'Type & condition confirmed'], ['step' => 'Baseline Labs', 'desc' => 'HbA1c, lipids, kidney function'], ['step' => 'Treatment Plan', 'desc' => 'Medications & lifestyle plan'], ['step' => 'Review', 'desc' => 'Lab trends assessed'], ['step' => 'Complication Screen', 'desc' => 'Annual checklist completed']],
        'benefits' => [
            ['icon' => 'gauge', 'color' => '#94a3b8', 'title' => 'Longitudinal metabolic tracking', 'desc' => 'Every HbA1c, lipid panel, and kidney function test plotted over time — instantly.'],
            ['icon' => 'shield-check', 'color' => '#94a3b8', 'title' => 'Complication prevention', 'desc' => 'Structured screening checklists ensure no diabetic complication assessment is missed.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Lab integration', 'desc' => 'OPES Lab results populate the ENDOIS dashboard automatically — no manual entry.'],
            ['icon' => 'landmark', 'color' => '#94a3b8', 'title' => 'NCD programme reporting', 'desc' => 'WHO and MoH NCD programme data exports built in.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-lab', 'pharmis', 'cardis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Device import', 'val' => 'Glucometer & CGM data'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['opes-emr', 'opes-lab', 'cardis'],
    ],

    'gynobsis' => [
        'slug' => 'gynobsis', 'name' => 'GYNOBSIS', 'subtitle' => 'Obstetrics & Gynaecology Information System',
        'category' => 'Specialist Systems', 'icon' => 'baby', 'color' => '#94a3b8',
        'tagline' => 'Complete OB/GYN system — antenatal care, labour & delivery records, postnatal follow-up, and gynaecology clinics.',
        'description' => 'GYNOBSIS manages the complete obstetrics and gynaecology workflow: antenatal booking and visit records following WHO ANC guidelines, partogram for labour monitoring, delivery records (including mode, outcome, APGAR scores), newborn registration linked to OPESCare Health ID, and postnatal follow-up scheduling.',
        'description2' => 'The gynaecology module provides structured clinical records for menstrual disorders, pelvic pathology, colposcopy reports, and surgical procedure documentation — all connected to OPES EMR and PHARMIS for prescriptions.',
        'target_users' => ['Hospital maternity wards and labour rooms', 'Antenatal care clinics', 'Gynaecology outpatient departments', 'Private OB/GYN practices', 'Maternal and child health (MCH) programme facilities'],
        'problems_solved' => [
            ['title' => 'Antenatal visits not systematically tracked', 'desc' => 'WHO ANC schedule tracked per pregnancy with automatic alerts for missed visits.'],
            ['title' => 'Partograms still on paper — not analysed', 'desc' => 'Digital partogram captures labour progress and alerts on abnormal patterns automatically.'],
            ['title' => 'Newborns not linked to mother\'s record at birth', 'desc' => 'Newborn automatically registered with OPESCare Health ID and linked to mother\'s record.'],
        ],
        'stats' => [['value' => 'WHO ANC', 'label' => 'guidelines built in'], ['value' => 'Digital', 'label' => 'partogram'], ['value' => 'Newborn', 'label' => 'Health ID at birth'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'baby', 'name' => 'Antenatal Care', 'desc' => 'WHO ANC schedule tracking with risk assessment, investigations, and referral management.', 'features' => ['WHO ANC visit schedule', 'Obstetric risk scoring', 'Lab orders (ANC panel)', 'Ultrasound report filing']],
            ['icon' => 'activity', 'name' => 'Labour & Delivery', 'desc' => 'Digital partogram, delivery records, and newborn assessment at birth.', 'features' => ['WHO partogram (digital)', 'Mode of delivery coding', 'APGAR scoring', 'Newborn OPESCare ID creation']],
            ['icon' => 'clipboard-list', 'name' => 'Gynaecology Clinic', 'desc' => 'Structured records for gynaecological consultations, procedures, and follow-up.', 'features' => ['Menstrual history templates', 'Pelvic examination records', 'Colposcopy report filing', 'Surgical procedure records']],
        ],
        'workflow' => [['step' => 'Booking', 'desc' => 'Pregnancy registered, EDD calculated'], ['step' => 'ANC Visits', 'desc' => 'WHO schedule tracked'], ['step' => 'Labour', 'desc' => 'Partogram recorded'], ['step' => 'Delivery', 'desc' => 'Outcome & newborn registered'], ['step' => 'Postnatal', 'desc' => 'Mother & baby follow-up']],
        'benefits' => [
            ['icon' => 'baby', 'color' => '#94a3b8', 'title' => 'WHO ANC compliance', 'desc' => 'Structured ANC schedule ensures every recommended visit and investigation is tracked.'],
            ['icon' => 'activity', 'color' => '#94a3b8', 'title' => 'Digital partogram', 'desc' => 'Labour progress tracked digitally with automatic alerts on prolonged labour patterns.'],
            ['icon' => 'fingerprint', 'color' => '#94a3b8', 'title' => 'Newborn Health ID at birth', 'desc' => 'Every newborn gets an OPESCare Health ID at delivery — starting life with a digital record.'],
            ['icon' => 'shield-check', 'color' => '#94a3b8', 'title' => 'Maternal health reporting', 'desc' => 'Maternal mortality, caesarean rate, and ANC coverage reports for MoH HMIS.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-lab', 'pharmis', 'paedis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Newborn registration', 'val' => 'Auto OPESCare Health ID'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['opes-emr', 'paedis', 'opes-lab'],
    ],

    'mhis' => [
        'slug' => 'mhis', 'name' => 'MHIS', 'subtitle' => 'Mental Health Information System',
        'category' => 'Specialist Systems', 'icon' => 'brain', 'color' => '#94a3b8',
        'tagline' => 'Sensitive, structured mental health records — assessments, therapy notes, medication management, and crisis care protocols.',
        'description' => 'MHIS provides structured clinical records for mental health facilities — psychiatric inpatient units, community mental health centres, addiction treatment programmes, and outpatient psychiatry clinics. It implements privacy-first data architecture, ensuring mental health records are accessible only to authorised mental health professionals.',
        'description2' => 'MHIS includes validated assessment tools (PHQ-9, GAD-7, AUDIT, CAGE, PANSS, YMRS) embedded in the clinical workflow, alongside structured therapy session notes, medication management (including depot injection scheduling), and crisis care protocols.',
        'target_users' => ['Psychiatric inpatient units', 'Community mental health centres', 'Addiction treatment and rehabilitation programmes', 'Outpatient psychiatry and psychology clinics', 'NGO mental health programmes'],
        'problems_solved' => [
            ['title' => 'Mental health records not appropriately privacy-protected', 'desc' => 'MHIS records are isolated from general OPES EMR access — only authorised MH professionals can view.'],
            ['title' => 'Validated assessment tools not used consistently', 'desc' => 'PHQ-9, GAD-7, PANSS, and other validated tools embedded in every assessment workflow.'],
            ['title' => 'Depot injection schedules missed', 'desc' => 'Automatic alerts for due depot injections and long-acting medication administrations.'],
        ],
        'stats' => [['value' => 'Privacy-first', 'label' => 'record architecture'], ['value' => '8+', 'label' => 'validated scales'], ['value' => 'Crisis', 'label' => 'care protocols'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'brain', 'name' => 'Psychiatric Assessment', 'desc' => 'Structured psychiatric assessment with MSE, risk assessment, and validated rating scales.', 'features' => ['Mental State Examination (MSE)', 'PHQ-9 · GAD-7 · PANSS · YMRS', 'Suicide & risk assessment tools', 'ICD-10 psychiatric diagnosis coding']],
            ['icon' => 'file-text', 'name' => 'Therapy & Session Notes', 'desc' => 'Structured notes for individual therapy, group sessions, and family therapy.', 'features' => ['Session type templates', 'Progress note SOAP format', 'Goal tracking & outcomes', 'Group session attendance']],
            ['icon' => 'pill', 'name' => 'Psychiatric Medication', 'desc' => 'Medication management with depot scheduling, side effect monitoring, and pharmacy integration.', 'features' => ['Depot injection schedule', 'Side effect rating scales (UKU)', 'Controlled substance registry', 'Integration with PHARMIS']],
        ],
        'workflow' => [['step' => 'Referral', 'desc' => 'From GP or self-referral'], ['step' => 'Assessment', 'desc' => 'Psychiatric & risk assessment'], ['step' => 'Diagnosis', 'desc' => 'ICD-10 coded'], ['step' => 'Treatment', 'desc' => 'Medication & therapy plan'], ['step' => 'Review', 'desc' => 'Outcome scales tracked over time']],
        'benefits' => [
            ['icon' => 'shield', 'color' => '#94a3b8', 'title' => 'Privacy-protected records', 'desc' => 'Mental health records isolated from general clinical access — only authorised MH professionals.'],
            ['icon' => 'brain', 'color' => '#94a3b8', 'title' => 'Validated assessment tools', 'desc' => 'PHQ-9, GAD-7, PANSS and more embedded — no paper forms, consistent application.'],
            ['icon' => 'clock', 'color' => '#94a3b8', 'title' => 'Depot injection alerts', 'desc' => 'Never miss a depot injection — automatic alerts for every due administration.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Pharmacy integration', 'desc' => 'Psychiatric medications prescribed directly to PHARMIS including controlled substances.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'pharmis', 'rehabis'],
        'specs' => [['group' => 'Privacy', 'rows' => [['key' => 'Record isolation', 'val' => 'Separate access control from OPES EMR'], ['key' => 'Encryption', 'val' => 'AES-256 at rest · TLS 1.3'], ['key' => 'Access', 'val' => 'Mental health professionals only'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['opes-emr', 'pharmis', 'rehabis'],
    ],

    'ndis' => [
        'slug' => 'ndis', 'name' => 'NDIS', 'subtitle' => 'Nutrition & Dietetics Information System',
        'category' => 'Specialist Systems', 'icon' => 'apple', 'color' => '#94a3b8',
        'tagline' => 'Nutritional assessment, dietary counselling records, malnutrition screening, and therapeutic feeding programme management.',
        'description' => 'NDIS supports dietitians and nutritionists in hospital and community settings. It provides structured nutritional assessment (using MUST, NRS-2002, and STAMP tools), dietary counselling records, therapeutic feeding programme management (SAM/MAM protocols), and integration with OPES Lab for nutritional biomarker tracking.',
        'description2' => 'Particularly relevant for Cameroon\'s malnutrition burden, NDIS tracks SAM and MAM cases across community feeding programmes with MUAC measurements, weight-for-height z-scores, and therapeutic food dispensing records.',
        'target_users' => ['Hospital dietetics departments', 'Paediatric malnutrition treatment centres', 'Community nutrition programmes (NGOs, MoH)', 'NCD clinics managing obesity and metabolic disease', 'Maternal nutrition programmes'],
        'problems_solved' => [
            ['title' => 'Malnutrition not identified at admission', 'desc' => 'MUST/NRS-2002 screening embedded in admission workflow — every at-risk patient flagged.'],
            ['title' => 'Therapeutic feeding not tracked systematically', 'desc' => 'SAM/MAM protocols with MUAC and weight tracking across every therapeutic feeding visit.'],
        ],
        'stats' => [['value' => 'MUST/NRS', 'label' => 'screening tools'], ['value' => 'SAM/MAM', 'label' => 'protocol support'], ['value' => 'MUAC', 'label' => 'tracking module'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'apple', 'name' => 'Nutritional Assessment', 'desc' => 'Validated malnutrition screening with MUST, NRS-2002, STAMP, and anthropometric measurements.', 'features' => ['MUST · NRS-2002 · STAMP scoring', 'Anthropometric measurements', 'BMI · Weight-for-height z-scores', 'MUAC measurement tracking']],
            ['icon' => 'clipboard-list', 'name' => 'Dietary Counselling', 'desc' => 'Structured dietary counselling records with food diary, plan, and review tracking.', 'features' => ['24-hour recall tool', 'Dietary plan templates', 'Food group adequacy scoring', 'Goal-setting & progress tracking']],
        ],
        'workflow' => [['step' => 'Screening', 'desc' => 'Malnutrition risk scored at admission'], ['step' => 'Assessment', 'desc' => 'Full nutritional assessment'], ['step' => 'Plan', 'desc' => 'Dietary plan & goals set'], ['step' => 'Review', 'desc' => 'Progress tracked'], ['step' => 'Discharge', 'desc' => 'Community follow-up plan']],
        'benefits' => [
            ['icon' => 'apple', 'color' => '#94a3b8', 'title' => 'Malnutrition screening built in', 'desc' => 'MUST and NRS-2002 screening at every admission — no patient at risk goes undetected.'],
            ['icon' => 'trending-up', 'color' => '#94a3b8', 'title' => 'Anthropometric tracking', 'desc' => 'Weight, MUAC, and z-scores tracked over time — progress visible at every review.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Lab integration', 'desc' => 'Nutritional biomarkers (albumin, pre-albumin, Hb) imported from OPES Lab automatically.'],
            ['icon' => 'landmark', 'color' => '#94a3b8', 'title' => 'Programme reporting', 'desc' => 'SAM/MAM programme outcomes exported for MoH, UNICEF, and WFP reporting.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'opes-lab', 'paedis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Mobile', 'val' => 'Tablet-optimised for community use'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['opes-emr', 'paedis', 'opes-lab'],
    ],

    'ophis' => [
        'slug' => 'ophis', 'name' => 'OPHIS', 'subtitle' => 'Ophthalmology Information System',
        'category' => 'Specialist Systems', 'icon' => 'eye', 'color' => '#94a3b8',
        'tagline' => 'Structured ophthalmology records — visual acuity, slit-lamp findings, fundus photography, surgical records, and spectacle prescriptions.',
        'description' => 'OPHIS provides a complete ophthalmology information system for eye clinics and hospital eye departments. It supports structured anterior and posterior segment examination records, refraction and spectacle prescription management, fundus photography filing, and surgical records for cataracts, glaucoma surgery, and other ophthalmic procedures.',
        'description2' => 'A particular strength for CEMAC facilities: OPHIS includes structured workflows for trachoma, cataract, glaucoma, and diabetic retinopathy screening programmes — conditions with high prevalence in the region.',
        'target_users' => ['Hospital eye departments', 'Standalone eye clinics and optometry centres', 'Preventive blindness programmes (cataract, trachoma)', 'Diabetic retinopathy screening programmes', 'Ophthalmic surgery centres'],
        'problems_solved' => [
            ['title' => 'Visual acuity records not tracked over time', 'desc' => 'BCVA and pinhole acuity recorded at every visit with trend graphs for each eye.'],
            ['title' => 'Diabetic retinopathy screening not systematic', 'desc' => 'Structured DR grading (ETDRS scale) with fundus photo filing and referral workflow.'],
        ],
        'stats' => [['value' => 'Visual Acuity', 'label' => 'longitudinal tracking'], ['value' => 'Fundus', 'label' => 'photography archive'], ['value' => 'DR Screening', 'label' => 'ETDRS grading'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'eye', 'name' => 'Clinical Examination', 'desc' => 'Structured anterior and posterior segment examination with standard notation.', 'features' => ['Visual acuity (Snellen & LogMAR)', 'IOP measurement & trend', 'Slit-lamp findings notation', 'Fundus examination templates']],
            ['icon' => 'image-up', 'name' => 'Imaging & Photography', 'desc' => 'Fundus photo and OCT image management with grading tools.', 'features' => ['Fundus photo archive', 'OCT image filing', 'DR grading (ETDRS)', 'Before/after surgical comparison']],
            ['icon' => 'glasses', 'name' => 'Refraction & Spectacles', 'desc' => 'Refraction records and spectacle prescription management.', 'features' => ['Auto-refractor import', 'Spectacle Rx printing', 'Contact lens fitting records', 'Low vision assessment']],
        ],
        'workflow' => [['step' => 'Registration', 'desc' => 'Patient & presenting complaint'], ['step' => 'Visual Acuity', 'desc' => 'VA measured & recorded'], ['step' => 'Examination', 'desc' => 'Slit-lamp & fundus assessed'], ['step' => 'Diagnosis', 'desc' => 'ICD-10 eye diagnosis'], ['step' => 'Plan', 'desc' => 'Rx · surgery · referral']],
        'benefits' => [
            ['icon' => 'eye', 'color' => '#94a3b8', 'title' => 'Structured eye examination', 'desc' => 'Every examination field documented consistently — anterior, posterior, IOP, and acuity.'],
            ['icon' => 'image-up', 'color' => '#94a3b8', 'title' => 'Fundus photo archive', 'desc' => 'Every fundus photograph stored and retrievable — track retinopathy progression objectively.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Diabetic retinopathy link', 'desc' => 'DR grading connects to ENDOIS diabetes record — both teams see the same patient.'],
            ['icon' => 'shield-check', 'color' => '#94a3b8', 'title' => 'Blindness prevention ready', 'desc' => 'Trachoma and cataract programme workflows built in for regional prevention programmes.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'endois', 'pharmis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Device interface', 'val' => 'Auto-refractor · OCT · Fundus camera'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['opes-emr', 'endois', 'pharmis'],
    ],

    'orthois' => [
        'slug' => 'orthois', 'name' => 'ORTHOIS', 'subtitle' => 'Orthotics & Prosthetics Information System',
        'category' => 'Specialist Systems', 'icon' => 'accessibility', 'color' => '#94a3b8',
        'tagline' => 'Manage orthotics and prosthetics assessments, device fabrication records, fitting, and long-term follow-up.',
        'description' => 'ORTHOIS supports orthotics and prosthetics (O&P) centres with structured clinical records for assessment, device prescription, fabrication tracking, fitting records, and long-term outcome monitoring. Connected to OPES EMR and REHABIS for multidisciplinary rehabilitation team coordination.',
        'target_users' => ['Orthotics & prosthetics centres', 'Hospital rehabilitation departments with O&P services', 'Disability rehabilitation programmes', 'War amputee and trauma rehabilitation centres', 'Paediatric orthotics services'],
        'problems_solved' => [
            ['title' => 'Device fabrication not tracked from prescription to delivery', 'desc' => 'Complete fabrication workflow tracked from assessment through fitting and follow-up.'],
            ['title' => 'No longitudinal outcome measurement for devices', 'desc' => 'Functional outcome measures tracked over time with patient satisfaction records.'],
        ],
        'stats' => [['value' => 'Full', 'label' => 'fabrication workflow'], ['value' => 'Outcome', 'label' => 'measurement tools'], ['value' => 'Rehab', 'label' => 'team integration'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'accessibility', 'name' => 'Assessment & Prescription', 'desc' => 'Structured O&P assessment with device prescription and material specification.', 'features' => ['Body segment assessment templates', 'Device prescription coding (ISO 9999)', 'Material & component specification', 'Referral from OPES EMR / REHABIS']],
            ['icon' => 'settings', 'name' => 'Fabrication Tracking', 'desc' => 'Track device from workshop order through fitting and delivery.', 'features' => ['Workshop job card', 'Fabrication stage tracking', 'Component inventory', 'Fitting appointment scheduling']],
        ],
        'workflow' => [['step' => 'Referral', 'desc' => 'From OPES EMR or REHABIS'], ['step' => 'Assessment', 'desc' => 'O&P assessment completed'], ['step' => 'Prescription', 'desc' => 'Device prescribed & ordered'], ['step' => 'Fabrication', 'desc' => 'Workshop tracking'], ['step' => 'Fitting & Follow-up', 'desc' => 'Outcome measured']],
        'benefits' => [
            ['icon' => 'accessibility', 'color' => '#94a3b8', 'title' => 'End-to-end device tracking', 'desc' => 'Every device tracked from prescription through workshop fabrication to patient fitting.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'Rehab team integration', 'desc' => 'Coordinates with REHABIS and OPES EMR for multidisciplinary rehabilitation planning.'],
            ['icon' => 'trending-up', 'color' => '#94a3b8', 'title' => 'Outcome measurement', 'desc' => 'Functional outcomes tracked over time — evidence of device effectiveness documented.'],
            ['icon' => 'package', 'color' => '#94a3b8', 'title' => 'Component inventory', 'desc' => 'Workshop component stock tracked — no fabrication delays from missing materials.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'rehabis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['rehabis', 'opes-emr', 'paedis'],
    ],

    'paedis' => [
        'slug' => 'paedis', 'name' => 'PAEDIS', 'subtitle' => 'Paediatrics Information System',
        'category' => 'Specialist Systems', 'icon' => 'shield-heart', 'color' => '#94a3b8',
        'tagline' => 'Complete paediatric records — growth charts, immunisation schedules, IMCI protocols, and neonatal intensive care.',
        'description' => 'PAEDIS provides structured paediatric clinical records from birth through adolescence. It includes WHO growth chart tracking (weight-for-age, height-for-age, weight-for-height, head circumference), vaccination schedule management per the Cameroon EPI programme, IMCI clinical decision support for under-5 illness management, and neonatal intensive care (NICU) records.',
        'description2' => 'Linked to GYNOBSIS for newborn registration at delivery and to OPES Lab for paediatric investigation ordering, PAEDIS gives paediatricians a complete longitudinal view of every child\'s health from birth.',
        'target_users' => ['Paediatric inpatient wards', 'Outpatient paediatrics and well-baby clinics', 'Neonatal intensive care units (NICU)', 'Vaccination centres and EPI programmes', 'Paediatric specialist services (cardiology, nephrology, oncology)'],
        'problems_solved' => [
            ['title' => 'Vaccination records lost or incomplete', 'desc' => 'Full Cameroon EPI vaccination history linked to OPESCare Health ID — never lost, never duplicated.'],
            ['title' => 'Growth faltering not detected early', 'desc' => 'WHO growth charts updated at every visit — z-score alerts flag faltering growth automatically.'],
            ['title' => 'IMCI protocols not consistently applied', 'desc' => 'IMCI decision support embedded in the under-5 consultation workflow for every clinician.'],
        ],
        'stats' => [['value' => 'WHO', 'label' => 'growth charts built in'], ['value' => 'EPI', 'label' => 'vaccination schedule'], ['value' => 'IMCI', 'label' => 'clinical decision support'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'trending-up', 'name' => 'Growth Monitoring', 'desc' => 'WHO growth charts with automatic z-score calculation and faltering growth alerts.', 'features' => ['Weight · Height · HC · BMI for age', 'WHO z-score calculations', 'Faltering growth alerts', 'Longitudinal growth curves']],
            ['icon' => 'shield-heart', 'name' => 'Vaccination (EPI)', 'desc' => 'Cameroon EPI schedule tracking with due-date alerts and batch number recording.', 'features' => ['Cameroon EPI schedule', 'Catch-up schedule support', 'Vaccine batch & lot numbers', 'Vaccination certificate printing']],
            ['icon' => 'stethoscope', 'name' => 'IMCI Clinical Support', 'desc' => 'WHO IMCI decision support for under-5 illness assessment and management.', 'features' => ['IMCI classify & treat algorithm', 'Danger sign alerts', 'Referral decision support', 'Case outcome recording']],
        ],
        'workflow' => [['step' => 'Birth Registration', 'desc' => 'OPESCare Health ID from GYNOBSIS'], ['step' => 'Newborn Check', 'desc' => 'NICU or well-baby assessment'], ['step' => 'Growth Monitoring', 'desc' => 'WHO charts updated every visit'], ['step' => 'Vaccinations', 'desc' => 'EPI schedule tracked'], ['step' => 'IMCI', 'desc' => 'Under-5 illness management']],
        'benefits' => [
            ['icon' => 'shield-heart', 'color' => '#94a3b8', 'title' => 'Complete child health record', 'desc' => 'Growth, vaccinations, illnesses, and development from birth through adolescence in one record.'],
            ['icon' => 'trending-up', 'color' => '#94a3b8', 'title' => 'Early growth faltering detection', 'desc' => 'WHO z-score alerts flag children falling behind growth curves before it becomes critical.'],
            ['icon' => 'shield-check', 'color' => '#94a3b8', 'title' => 'EPI compliance', 'desc' => 'No child falls behind on vaccinations — automatic alerts for every due dose.'],
            ['icon' => 'stethoscope', 'color' => '#94a3b8', 'title' => 'IMCI at every consultation', 'desc' => 'Evidence-based IMCI protocols guide under-5 illness management for all clinicians.'],
        ],
        'integrations' => ['opescare', 'gynobsis', 'opes-emr', 'opes-lab', 'ndis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Growth standards', 'val' => 'WHO 2006 Child Growth Standards'], ['key' => 'Vaccines', 'val' => 'Cameroon EPI + supplementary'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['gynobsis', 'ndis', 'opes-emr'],
    ],

    'rehabis' => [
        'slug' => 'rehabis', 'name' => 'REHABIS', 'subtitle' => 'Physical Medicine & Rehabilitation Information System',
        'category' => 'Specialist Systems', 'icon' => 'dumbbell', 'color' => '#94a3b8',
        'tagline' => 'Structured rehabilitation records — physiotherapy, occupational therapy, speech therapy, and multidisciplinary team coordination.',
        'description' => 'REHABIS provides a complete rehabilitation information system for physiotherapy, occupational therapy, and multidisciplinary rehabilitation teams. It includes structured functional assessment tools (Barthel Index, FIM, Berg Balance Scale), goal-setting with outcome tracking, session records for individual and group therapy, and integration with ORTHOIS for prosthetics and orthotics coordination.',
        'description2' => 'REHABIS supports rehabilitation pathways for stroke, traumatic brain injury, orthopaedic surgery, spinal cord injury, and chronic musculoskeletal conditions — tracking patient progress from acute rehabilitation through community reintegration.',
        'target_users' => ['Hospital physiotherapy departments', 'Rehabilitation centres and long-term care facilities', 'Stroke and neurological rehabilitation units', 'Orthopaedic post-surgical rehabilitation', 'Community rehabilitation programmes'],
        'problems_solved' => [
            ['title' => 'Rehabilitation goals not set or tracked', 'desc' => 'SMART goal-setting with regular review — progress tracked using validated outcome measures.'],
            ['title' => 'MDT communication fragmented', 'desc' => 'Shared MDT notes and goal board visible to all team members — physio, OT, speech, nursing, and doctor.'],
        ],
        'stats' => [['value' => 'Barthel · FIM', 'label' => 'outcome measures'], ['value' => 'MDT', 'label' => 'shared goal board'], ['value' => 'ORTHOIS', 'label' => 'O&P integration'], ['value' => 'EN/FR', 'label' => 'bilingual']],
        'modules' => [
            ['icon' => 'dumbbell', 'name' => 'Functional Assessment', 'desc' => 'Validated functional outcome measures at admission, discharge, and follow-up.', 'features' => ['Barthel Index · FIM', 'Berg Balance Scale', 'Oxford Muscle Strength grading', 'Pain scale (NRS/VAS)']],
            ['icon' => 'target', 'name' => 'Goal Setting & Therapy', 'desc' => 'SMART rehabilitation goals with session records and outcome tracking.', 'features' => ['SMART goal templates', 'Session record by discipline', 'Group therapy attendance', 'Home exercise programme printing']],
            ['icon' => 'users', 'name' => 'MDT Coordination', 'desc' => 'Shared team goal board and communication notes for multidisciplinary rehabilitation.', 'features' => ['Shared MDT goal board', 'Cross-discipline notes', 'MDT meeting records', 'Discharge summary generation']],
        ],
        'workflow' => [['step' => 'Referral', 'desc' => 'From OPES EMR or hospital'], ['step' => 'Assessment', 'desc' => 'Barthel / FIM scored'], ['step' => 'Goals Set', 'desc' => 'MDT SMART goal plan'], ['step' => 'Therapy', 'desc' => 'Sessions recorded'], ['step' => 'Review', 'desc' => 'Outcomes measured & goals updated']],
        'benefits' => [
            ['icon' => 'dumbbell', 'color' => '#94a3b8', 'title' => 'Validated outcome measures', 'desc' => 'Barthel, FIM, and Berg Balance tracked — objective evidence of rehabilitation progress.'],
            ['icon' => 'users', 'color' => '#94a3b8', 'title' => 'True MDT working', 'desc' => 'Shared goal board and notes — every team member sees the same patient goals and progress.'],
            ['icon' => 'link', 'color' => '#94a3b8', 'title' => 'O&P integration', 'desc' => 'ORTHOIS device fabrication coordinated directly from the REHABIS rehabilitation plan.'],
            ['icon' => 'home', 'color' => '#94a3b8', 'title' => 'Community discharge planning', 'desc' => 'Home exercise programmes and community referrals built into the discharge workflow.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'orthois', 'mhis', 'sltis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Mobile', 'val' => 'Tablet-optimised for therapy sessions'], ['key' => 'Languages', 'val' => 'English · French']]]],
        'related' => ['orthois', 'mhis', 'sltis'],
    ],

    'sltis' => [
        'slug' => 'sltis', 'name' => 'SLTIS', 'subtitle' => 'Speech & Language Therapy Information System',
        'category' => 'Specialist Systems', 'icon' => 'waves', 'color' => '#94a3b8',
        'tagline' => 'Structured speech and language therapy records — assessment, therapy plans, session records, and outcome measurement.',
        'description' => 'SLTIS provides structured clinical records for speech and language therapists working with adults and children. It supports communication disorder assessment (aphasia, dysarthria, dysphagia, language delay, stuttering), structured therapy planning with evidence-based approaches, session records, and outcome measurement using validated tools.',
        'description2' => 'Particularly relevant in the bilingual CEMAC context, SLTIS is designed for therapists working in both English and French — with assessment tools and therapy resources available in both languages for monolingual and bilingual patients.',
        'target_users' => ['Hospital speech and language therapy departments', 'Paediatric SLT services (language delay, autism, cleft palate)', 'Neurorehabilitation units (stroke aphasia, traumatic brain injury)', 'Dysphagia management services', 'Private SLT practices'],
        'problems_solved' => [
            ['title' => 'SLT assessment results not standardised', 'desc' => 'Validated assessment tools (BDAE, CELF, SSI) built into the assessment workflow.'],
            ['title' => 'Dysphagia management not documented systematically', 'desc' => 'Structured IDDSI framework dysphagia assessment with diet and fluid modification records.'],
        ],
        'stats' => [['value' => 'Adult & Paeds', 'label' => 'SLT assessment tools'], ['value' => 'IDDSI', 'label' => 'dysphagia framework'], ['value' => 'EN/FR', 'label' => 'bilingual (rare in SLT)'], ['value' => 'MDT', 'label' => 'integration via REHABIS']],
        'modules' => [
            ['icon' => 'waves', 'name' => 'Communication Assessment', 'desc' => 'Standardised assessment tools for aphasia, dysarthria, language delay, and stuttering.', 'features' => ['Aphasia assessment (BDAE / WAB adapted)', 'Dysarthria severity rating', 'Paediatric language assessment', 'Stuttering severity (SSI-4)']],
            ['icon' => 'clipboard-list', 'name' => 'Dysphagia Management', 'desc' => 'IDDSI framework assessment with diet and fluid modification recommendations.', 'features' => ['IDDSI levels 0–7 assessment', 'Bedside swallow assessment template', 'VFSS / FEES report filing', 'Diet modification recommendation']],
            ['icon' => 'target', 'name' => 'Therapy Planning', 'desc' => 'Evidence-based therapy programme planning with session records and outcome tracking.', 'features' => ['Goal-based therapy plans', 'Session record templates', 'Home programme printing', 'Outcome measure trend graphs']],
        ],
        'workflow' => [['step' => 'Referral', 'desc' => 'From OPES EMR / paeds / rehab'], ['step' => 'Assessment', 'desc' => 'Validated tools applied'], ['step' => 'Therapy Plan', 'desc' => 'Evidence-based goals set'], ['step' => 'Sessions', 'desc' => 'Progress recorded'], ['step' => 'Review', 'desc' => 'Outcome measures updated']],
        'benefits' => [
            ['icon' => 'waves', 'color' => '#94a3b8', 'title' => 'Standardised assessments', 'desc' => 'Validated SLT tools built in — consistent, evidence-based assessments every time.'],
            ['icon' => 'shield-check', 'color' => '#94a3b8', 'title' => 'Dysphagia safety', 'desc' => 'IDDSI-based dysphagia assessment protects patients with swallowing disorders from aspiration.'],
            ['icon' => 'languages', 'color' => '#94a3b8', 'title' => 'Bilingual (English & French)', 'desc' => 'Rare in SLT software globally — essential for CEMAC\'s bilingual population.'],
            ['icon' => 'users', 'color' => '#94a3b8', 'title' => 'MDT integration', 'desc' => 'Connects to REHABIS for shared rehabilitation team goal boards and MDT meeting records.'],
        ],
        'integrations' => ['opescare', 'opes-emr', 'rehabis', 'paedis'],
        'specs' => [['group' => 'Deployment', 'rows' => [['key' => 'Options', 'val' => 'On-premise · Cloud'], ['key' => 'Languages', 'val' => 'English · French (interface & assessment tools)'], ['key' => 'Mobile', 'val' => 'Tablet-optimised']]]],
        'related' => ['rehabis', 'paedis', 'opes-emr'],
    ],

];
